### ISSUE TITLE
when use code-server install this extension got not found

### ISSUE THREAD

**Issue by humbinal** [cwan/native-ascii-converter#18]
Hi cwan:

when is use code-server install this extension， I got not found error。
```
$ code-server --install-extension cwan.native-ascii-converter
Extension 'cwan.native-ascii-converter' not found.
[2021-05-28T06:42:50.703Z] error vscode Error: Failed Installing Extensions: cwan.native-ascii-converter
    at O.installExtensions (/usr/local/code-server/lib/vscode/out/vs/server/entry.js:19:42)
    at async /usr/local/code-server/lib/vscode/out/vs/server/entry.js:36:90861
    at async M (/usr/local/code-server/lib/vscode/out/vs/server/entry.js:36:94206)
    at async process.<anonymous> (/usr/local/code-server/lib/vscode/out/vs/server/entry.js:36:103823)
```

1. I download the .vsix file manually from code-server and install, It was OK。
2. I also test use `code --install-extension cwan.native-ascii-converter `, It was OK。
3. I use `code-server --install-extension ...` installed very much extensions is also OK。

This question bothers me very much，can you help me?

**Comment by cwan** [comment]
I guess it's because code-server references [Open VSX Registory](https://open-vsx.org/) not [Visual Studio Marketplace](https://marketplace.visualstudio.com/).
I will try to register it for Open VSX Registory.

**Comment by humbinal** [comment]
@cwan thank you, you solved my problems.

**Comment by cwan** [comment]
I claimed namespace "cwan", and it was granted. I signed the publisher agreement then reuploaded a vsix file. But apparently not enough... I gave it up.
https://open-vsx.org/extension/cwan/native-ascii-converter
https://github.com/EclipseFdn/open-vsx.org/issues/539
